services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: 'zookeeper'
    env_file:
      - kafka.env
    ports:
      - "22181:2181"
    networks:
      - mynetwork

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: 'kafka'
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
      - "9092:9092"
    env_file:
      - kafka.env
    networks:
      - mynetwork

  postgres:
    image: 'postgres:15'
    container_name: 'postgres'
    ports:
      - "5432:5432"
    env_file:
      - db.env
    networks:
      - mynetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  deal:
    build: ./deal
    container_name: 'deal'
    depends_on:
      - postgres
      - zookeeper
      - kafka
    env_file:
      - ./deal/.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8081:8081"

  calculator:
    build: ./calculator
    container_name: 'calculator'
    depends_on:
      - postgres
      - deal
      - zookeeper
      - kafka
    env_file:
      - ./calculator/.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8080:8080"

  statement:
    build: ./statement
    container_name: 'statement'
    depends_on:
      - postgres
      - deal
      - calculator
      - zookeeper
      - kafka
    env_file:
      - ./statement/.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8082:8082"

  dossier:
    build: ./dossier
    container_name: 'dossier'
    depends_on:
      - postgres
      - deal
      - calculator
      - statement
      - zookeeper
      - kafka
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8083:8083"

  gateway:
    build: ./gateway
    container_name: 'gateway'
    depends_on:
      - postgres
      - deal
      - calculator
      - statement
      - dossier
      - zookeeper
      - kafka
    env_file:
      - ./gateway/.env
    restart: on-failure
    networks:
      - mynetwork
    ports:
      - "8888:8888"

  grafana:
    image: grafana/grafana:latest
    container_name: 'grafana'
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - grafana.env
    depends_on:
      - loki
      - prometheus
    restart: on-failure
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus:latest
    container_name: 'prometheus'
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
      - ./prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: on-failure
    networks:
      - mynetwork

  loki:
    image: grafana/loki:latest
    container_name: 'loki'
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    env_file:
      - app.env
    restart: on-failure
    networks:
      - mynetwork

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: 'jaeger'
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_OTLP_HOST=0.0.0.0
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db-data:
    driver: local
  loki_data:
    driver: local