{
 "title": "Продуктовые метрики: Заявки и Кредиты",
 "description": "Продуктовые метрики: заявки и кредиты",
 "tags": [
  "product",
  "loans"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Ключевые показатели", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Всего заявок (за час)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(product_loan_applications_total)"
    }
   ]
  },
  {
   "title": "Всего выдано кредитов (за час)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(product_credit_issued_total)"
    }
   ]
  },
  {
   "title": "Процент одобрения",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "product_approval_rate_percent / 100"
    }
   ]
  },
  {
   "title": "Конверсия в выдачу",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "product_conversion_rate_percent / 100"
    }
   ]
  },
  {
   "title": "Заявки в минуту по сервисам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (product_loan_applications_per_minute)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Процентные метрики",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "product_approval_rate_percent", "legendFormat": "Процент одобрения" },
    {
     "expr": "product_conversion_rate_percent",
     "legendFormat": "Конверсия в выдачу"
    }
   ]
  },
  {
   "title": "Топ-5 сервисов по заявкам",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "topk(5, product_loan_applications_per_minute)"
    }
   ]
  }
 ]
}