server:
  port: 8888

other:
  service:
    url:
      deal: ${DEAL_SERVICE:http://localhost:8081/deal}
      statement: ${STATEMENT_SERVICE:http://localhost:8082/statement}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

loki:
  url: ${LOKI_ENDPOINT:http://localhost:3100/loki/api/v1/push}