name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: deal-service
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build common with Maven
#        env:
#          POSTGRES_HOST: localhost
#          POSTGRES_PORT: 5433
#          POSTGRES_DB: deal-service
        run: mvn -B clean package --file pom.xml

#      - name: Build MS-api with Maven
#        run: mvn -B clean package --file ./api/pom.xml
#
#      - name: Build MS-statement with Maven
#        run: mvn -B clean package --file ./statement/pom.xml
#
#      - name: Build MS-calculator with Maven
#        run: mvn -B clean package --file ./calculator/pom.xml
#
#      - name: Build MS-deal with Maven
#        run: mvn -B clean package --file ./deal/pom.xml
#
#      - name: Build MS-dossier with Maven
#        run: mvn -B clean package --file ./dossier/pom.xml
#
#      - name: Build MS-gateway with Maven
#        run: mvn -B clean package --file ./gateway/pom.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}